language: node_js
node_js:
  - "6.2.1"
install:
- npm install
script:
  - npm run lint
  - npm test
  - npm run test:cov
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
sudo: false
